server:
  port: 8071
  servlet:
    context-path: /task

#spring:
#  mail:
#    host: smtp.gmail.com
#    username: jeffchung030@gmail.com
#    password: 321456ze
#    protocol: smtp
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 465
#    properties.mail.display.sendmail: Javen
#    properties.mail.display.sendname: Spring Boot Guide Email
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#    properties:
#      "[mail.smtp.connectiontimeout]": 5000
#      "[mail.smtp.timeout]": 3000
#      "[mail.smtp.writetimeout]": 5000
spring:
  application:
    name: test-task
